### ISSUE TITLE
MathSlate bug on Moodle 2.5

### ISSUE THREAD

**Issue by luguel** [dthies/moodle-editor_tinymce-mathslate#4]
Hi everyone, I have a problem when I display the MathSlate popup it show an unknown error. Anyone else presents this problem? What can I do?

I am using Moodle 2.5 and the TinyMCE Editor.

![mathslate](https://cloud.githubusercontent.com/assets/11652916/6832538/d8f7ff8e-d2ec-11e4-8c1f-d83b676b17af.JPG)

**Comment by dthies** [comment]
This was a Firefox bug that resolved itself.
