### ISSUE TITLE
Do not work on Moodle 3.4.1+

### ISSUE THREAD

**Issue by egamby** [dthies/moodle-editor_tinymce-mathslate#5]
Hi,

I did a fresh install of Moodle 3.4.1+ (20180118), installed the latest version of the plugin and kept default configuration.

When I try to create an equation, there are [Math Error] everywhere in the dialog box. Firebug reports a lot of 404 errors:

NetworkError: 404 Not Found - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/jax/output/HTML-CSS/fonts/TeX/TeX/fontdata.js?V=2.7.1
TypeError: this.loading[i] is undefined
NetworkError: 404 Not Found - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/fonts/HTML-CSS/TeX/TeX/woff/MathJax_Size4-Regular.woff?V=2.7.1
NetworkError: 404 Not Found - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/fonts/HTML-CSS/TeX/TeX/woff/MathJax_Math-Italic.woff?V=2.7.1
NetworkError: 404 Not Found - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/fonts/HTML-CSS/TeX/TeX/woff/MathJax_Main-Regular.woff?V=2.7.1
NetworkError: 404 Not Found - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/fonts/HTML-CSS/TeX/TeX/woff/MathJax_Size1-Regular.woff?V=2.7.1
NetworkError: 404 Not Found - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/fonts/HTML-CSS/TeX/TeX/otf/MathJax_Size4-Regular.otf?V=2.7.1
NetworkError: 404 Not Found - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/fonts/HTML-CSS/TeX/TeX/otf/MathJax_Math-Italic.otf?V=2.7.1
NetworkError: 404 Not Found - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/fonts/HTML-CSS/TeX/TeX/otf/MathJax_Main-Regular.otf?V=2.7.1
NetworkError: 404 Not Found - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/fonts/HTML-CSS/TeX/TeX/otf/MathJax_Size1-Regular.otf?V=2.7.1
NetworkError: 404 Not Found - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/fonts/HTML-CSS/TeX/TeX/png/imagedata.js?V=2.7.1
TypeError: c.FONTDATA.FONTS.MathJax_Main[8212][5] is undefined 

In particular, It looks strange to me than the 'TeX' path is repeated in the URL. If I type the same URL without the duplicate 'TeX' in my browser, it works.

I also tried with a local copy and ran the test application of MathJax (which was OK), fixed the paths, this looked better but still didn't work.

I have also the same behaviour with Chomium.

Best Regards,
Emmanuel

**Comment by dthies** [comment]
Hi Emmanuel,
I had not seen this. It seems to be a problem with the Safe extension that is added in. I am able to reproduce what you are seeing and to fix it by removing Safe from mathslate.php. I don't know what has changed at the moment to cause this problem.
Thanks,
Daniel

**Comment by dthies** [comment]
I retested Moodle 3.0 and it works out to the box. Therefore this is likely caused by the upgrade.

**Comment by dthies** [comment]
There was a change in the way the MathJax filter configuration was loaded in Moodle 3.2 that caused a confilct. I  changed the way Mathslate loads if the filter is enabled. The most recent versions should work.

**Comment by egamby** [comment]
Hello,
Sorry for my late reply. I confirm that it solved my issue.
Thank you for the fix!
Emmanuel

**Comment by dthies** [comment]
Thank you very much for the feedback.

**Comment by labapen** [comment]
Hi, 
I installed the plugin in Moodle 4.0, but when I try to write an equation, the pop-up window is blank. How can you help me?
